### PR TITLE
(maint) These haven't been relevant for over a year

### PR DESCRIPTION
**Pull request by binford2k**

### CODE REVIEW

**Comment by marrero984** [comment]
@binford2k What are 'these'?

**Comment by binford2k** [comment]
the files deleted in this PR.

**Comment by marrero984** [comment]
What did they do and why are they no longer relevant?

**Comment by binford2k** [comment]
https://github.com/puppetlabs/education-builds/pull/853/files#diff-52a13cfb225ffc08e965e9387653de01L1

As to why it's no longer relevant, when was the last time you started a class like this?

**Pull request merged**
