### PR TITLE
Various updates/fixes to support PE 2019.0.1

### PR DESCRIPTION
**Pull request by greglarkin**

### CODE REVIEW

**Comment by greglarkin** [comment]
I am struggling to understand why a lot of the changes in the pltraining-bootstrap repository were needed on top of many of the changes here. The bootstrap changes are: https://github.com/puppetlabs/pltraining-bootstrap/compare/6aa798a90014481b0d200d2e54e439ede683ee42...master

**Comment by greglarkin** [comment]
Now I understand - the LVM build uses the *legacy* branch of the bootstrap repository, not the *master* branch. :(

**Comment by greglarkin** [comment]
@acidprime @thedarkwriter Ready for review

**Comment by orcutt989** [comment]
Added some comments to the Readme for easy setup, but no errors during build! Great job!

**Pull request merged**
